### ISSUE TITLE
Read + Present Financial Diaries

### ISSUE THREAD

**Issue by kuljotanand** [Cash-Economy/BMGF#16]
#### Mark 'done' on issues list once you've read, understood and prepared a summary (verbal is OK but take notes) to share with your teammates on Sunday, Sep 18 2016.

Johanan:
- Mateo And Lucia: Thriving But Still Vulnerable In The U.S.: http://www.usfinancialdiaries.org/house10-ny
- Elena Navarro: Getting Through A Tough Year: http://www.usfinancialdiaries.org/house9-ca
- [x] complete?

Mario:
- Sandra Young: Budgeting For A Year With Lumpy Income: http://www.usfinancialdiaries.org/house8-ny
- Lauren Walker: Getting By With Limited Resources: http://www.usfinancialdiaries.org/house7-ms
- [x] complete?

Aamer:
- Rita Douglas: Getting By With Help From Friends: http://www.usfinancialdiaries.org/house6-oh
- Mike Smith: Keeping Control By Relying On Cash: http://www.usfinancialdiaries.org/house4-ky
- [x] complete?

Alan:
- The Hossains: Adjusting To A New Life In The US: http://www.usfinancialdiaries.org/house3-ny
- The Adrians: Relying On Erratic Income Sources: http://www.usfinancialdiaries.org/house5-mi
- [x] complete?

Kuljot:
- The Johnsons: Working Hard But Still Struggling: http://www.usfinancialdiaries.org/house2-oh
- The Rodriguez Family: Extended Family Strives To Get Ahead: http://www.usfinancialdiaries.org/house1-ca
- [x] complete?

**Comment by ajtlau** [comment]
[Financial Narratives_AL.docx](https://github.com/Cash-Economy/BMGF/files/478758/Financial.Narratives_AL.docx)

**Comment by oatsandsugar** [comment]
[Financial Narratives JCO](https://github.com/Cash-Economy/BMGF/blob/master/research/US%20Financial%20Diaries%20-%20summary%20of%20families.md)

Annotated articles:
[Family 1.pdf](https://github.com/Cash-Economy/BMGF/files/478899/Family.1.pdf)
[Family 2.pdf](https://github.com/Cash-Economy/BMGF/files/478900/Family.2.pdf)
