### ISSUE TITLE
Speak to 3 individuals who operate in the cash economy in NYC

### ISSUE THREAD

**Issue by kuljotanand** [Cash-Economy/BMGF#17]
<b>Discovery process</b>
- Casual conversation with 3 individuals who operate in the cash economy.
- Don't turn it into a forced interview -- just try to understand their genuine perspective. an "interview" may result in fake responses.

We are just trying to gauge why people operate in a cash economy even when they have access to a lot of infrastructure/services.
- [x] @oatsandsugar
- [ ] @kuljotanand 
- [ ] @MarioRial22 
- [x] @AHassanally 
- [ ] @ajtlau

**Comment by oatsandsugar** [comment]
- [ ] @oatsandsugar
- [ ] @kuljotanand 
- [ ] @MarioRial22 
- [ ] @AHassanally 
- [ ] @ajtlau

**Comment by oatsandsugar** [comment]
https://github.com/Cash-Economy/BMGF/blob/master/research/Vox%20Populi.md
