### ISSUE TITLE
Re-run systems diagram 

### ISSUE THREAD

**Issue by kuljotanand** [Cash-Economy/BMGF#18]
With our new focus on the US based cash economy participants, run a new system's diagram.

**Comment by oatsandsugar** [comment]
No real amendments to diagram structure, some amendments to directionality required to reflect learnings from [research](https://github.com/Cash-Economy/BMGF/blob/master/research/US%20Financial%20Diaries%20-%20summary%20of%20families.md), specifically:

> There is no binary distinction between cash and non-cash economy actors.
> 
> Actors who participate primarily in the cash economy tend to have some exposure to the non-cash economy - usually in the form of a chequing account that wages are paid into.
