### ISSUE TITLE
Discuss + sign team agreement (vis. goals & expectations)

### ISSUE THREAD

**Issue by AHassanally** [Cash-Economy/BMGF#19]
As well as Individual goals posted to [Goals page](https://github.com/Cash-Economy/BMGF/tree/master/Artifacts/elements/goals)
- [x] JCO
- [x] AH
- [x] AL
- [x] KJ
- [x] MR

**Comment by oatsandsugar** [comment]
Thanks @AHassanally for the draft of the agreement - I have put my comments in
