### ISSUE TITLE
Send Company Champion Recap of Action Items

### ISSUE THREAD

**Issue by ajtlau** [Cash-Economy/BMGF#25]
Set up weekly touchpoint
Send out to dos
Send out availability for conference

**Comment by oatsandsugar** [comment]
Incorporate this into the weekly email

**Comment by oatsandsugar** [comment]
see https://github.com/Cash-Economy/BMGF/blob/master/Artifacts/Status-Report/Status%20Report%203.md

**Comment by oatsandsugar** [comment]
Incorporate into https://github.com/Cash-Economy/BMGF/issues/24
